//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D3Hot.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int cb_trig_tmr1 {
            get {
                return ((int)(this["cb_trig_tmr1"]));
            }
            set {
                this["cb_trig_tmr1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int cb_trig_tmr2 {
            get {
                return ((int)(this["cb_trig_tmr2"]));
            }
            set {
                this["cb_trig_tmr2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int cb_trig_tmr3 {
            get {
                return ((int)(this["cb_trig_tmr3"]));
            }
            set {
                this["cb_trig_tmr3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int cb_trig_tmr4 {
            get {
                return ((int)(this["cb_trig_tmr4"]));
            }
            set {
                this["cb_trig_tmr4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cb_key1 {
            get {
                return ((int)(this["cb_key1"]));
            }
            set {
                this["cb_key1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int cb_key2 {
            get {
                return ((int)(this["cb_key2"]));
            }
            set {
                this["cb_key2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int cb_key3 {
            get {
                return ((int)(this["cb_key3"]));
            }
            set {
                this["cb_key3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int cb_key4 {
            get {
                return ((int)(this["cb_key4"]));
            }
            set {
                this["cb_key4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_tmr1 {
            get {
                return ((decimal)(this["nud_tmr1"]));
            }
            set {
                this["nud_tmr1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_tmr2 {
            get {
                return ((decimal)(this["nud_tmr2"]));
            }
            set {
                this["nud_tmr2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_tmr3 {
            get {
                return ((decimal)(this["nud_tmr3"]));
            }
            set {
                this["nud_tmr3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_tmr4 {
            get {
                return ((decimal)(this["nud_tmr4"]));
            }
            set {
                this["nud_tmr4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cb_prog {
            get {
                return ((int)(this["cb_prog"]));
            }
            set {
                this["cb_prog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cb_pause {
            get {
                return ((int)(this["cb_pause"]));
            }
            set {
                this["cb_pause"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lb_lang {
            get {
                return ((string)(this["lb_lang"]));
            }
            set {
                this["lb_lang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int prof_curr {
            get {
                return ((int)(this["prof_curr"]));
            }
            set {
                this["prof_curr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int cb_trig_tmr5 {
            get {
                return ((int)(this["cb_trig_tmr5"]));
            }
            set {
                this["cb_trig_tmr5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int cb_trig_tmr6 {
            get {
                return ((int)(this["cb_trig_tmr6"]));
            }
            set {
                this["cb_trig_tmr6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int cb_key5 {
            get {
                return ((int)(this["cb_key5"]));
            }
            set {
                this["cb_key5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int cb_key6 {
            get {
                return ((int)(this["cb_key6"]));
            }
            set {
                this["cb_key6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_tmr5 {
            get {
                return ((decimal)(this["nud_tmr5"]));
            }
            set {
                this["nud_tmr5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_tmr6 {
            get {
                return ((decimal)(this["nud_tmr6"]));
            }
            set {
                this["nud_tmr6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int cb_startstop {
            get {
                return ((int)(this["cb_startstop"]));
            }
            set {
                this["cb_startstop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T")]
        public string cb_tp {
            get {
                return ((string)(this["cb_tp"]));
            }
            set {
                this["cb_tp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int cb_tpdelay {
            get {
                return ((int)(this["cb_tpdelay"]));
            }
            set {
                this["cb_tpdelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int chb_tray {
            get {
                return ((int)(this["chb_tray"]));
            }
            set {
                this["chb_tray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int chb_mult {
            get {
                return ((int)(this["chb_mult"]));
            }
            set {
                this["chb_mult"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cb_key_delay {
            get {
                return ((string)(this["cb_key_delay"]));
            }
            set {
                this["cb_key_delay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_key_delay_ms {
            get {
                return ((decimal)(this["nud_key_delay_ms"]));
            }
            set {
                this["nud_key_delay_ms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int chb_trig1 {
            get {
                return ((int)(this["chb_trig1"]));
            }
            set {
                this["chb_trig1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int chb_trig2 {
            get {
                return ((int)(this["chb_trig2"]));
            }
            set {
                this["chb_trig2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int chb_trig3 {
            get {
                return ((int)(this["chb_trig3"]));
            }
            set {
                this["chb_trig3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int chb_trig4 {
            get {
                return ((int)(this["chb_trig4"]));
            }
            set {
                this["chb_trig4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int chb_trig5 {
            get {
                return ((int)(this["chb_trig5"]));
            }
            set {
                this["chb_trig5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int chb_trig6 {
            get {
                return ((int)(this["chb_trig6"]));
            }
            set {
                this["chb_trig6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int chb_hold {
            get {
                return ((int)(this["chb_hold"]));
            }
            set {
                this["chb_hold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int chb_mpress {
            get {
                return ((int)(this["chb_mpress"]));
            }
            set {
                this["chb_mpress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int chb_saveload {
            get {
                return ((int)(this["chb_saveload"]));
            }
            set {
                this["chb_saveload"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_rand {
            get {
                return ((decimal)(this["nud_rand"]));
            }
            set {
                this["nud_rand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cb_hot_prof {
            get {
                return ((int)(this["cb_hot_prof"]));
            }
            set {
                this["cb_hot_prof"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_prof_name {
            get {
                return ((string)(this["tb_prof_name"]));
            }
            set {
                this["tb_prof_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Profile 1")]
        public string profile1 {
            get {
                return ((string)(this["profile1"]));
            }
            set {
                this["profile1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Profile 2")]
        public string profile2 {
            get {
                return ((string)(this["profile2"]));
            }
            set {
                this["profile2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Profile 3")]
        public string profile3 {
            get {
                return ((string)(this["profile3"]));
            }
            set {
                this["profile3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M")]
        public string cb_map {
            get {
                return ((string)(this["cb_map"]));
            }
            set {
                this["cb_map"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cb_mapdelay {
            get {
                return ((int)(this["cb_mapdelay"]));
            }
            set {
                this["cb_mapdelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int chb_users {
            get {
                return ((int)(this["chb_users"]));
            }
            set {
                this["chb_users"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int chb_proconly {
            get {
                return ((int)(this["chb_proconly"]));
            }
            set {
                this["chb_proconly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cb_key1_desc {
            get {
                return ((string)(this["cb_key1_desc"]));
            }
            set {
                this["cb_key1_desc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cb_key2_desc {
            get {
                return ((string)(this["cb_key2_desc"]));
            }
            set {
                this["cb_key2_desc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cb_key3_desc {
            get {
                return ((string)(this["cb_key3_desc"]));
            }
            set {
                this["cb_key3_desc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cb_key4_desc {
            get {
                return ((string)(this["cb_key4_desc"]));
            }
            set {
                this["cb_key4_desc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cb_key5_desc {
            get {
                return ((string)(this["cb_key5_desc"]));
            }
            set {
                this["cb_key5_desc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cb_key6_desc {
            get {
                return ((string)(this["cb_key6_desc"]));
            }
            set {
                this["cb_key6_desc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cb_tp_desc {
            get {
                return ((string)(this["cb_tp_desc"]));
            }
            set {
                this["cb_tp_desc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cb_map_desc {
            get {
                return ((string)(this["cb_map_desc"]));
            }
            set {
                this["cb_map_desc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cb_key_delay_desc {
            get {
                return ((string)(this["cb_key_delay_desc"]));
            }
            set {
                this["cb_key_delay_desc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int chb_ver_check {
            get {
                return ((int)(this["chb_ver_check"]));
            }
            set {
                this["chb_ver_check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int pos_x {
            get {
                return ((int)(this["pos_x"]));
            }
            set {
                this["pos_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int pos_y {
            get {
                return ((int)(this["pos_y"]));
            }
            set {
                this["pos_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cb_returndelay {
            get {
                return ((int)(this["cb_returndelay"]));
            }
            set {
                this["cb_returndelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cb_tmr1 {
            get {
                return ((int)(this["cb_tmr1"]));
            }
            set {
                this["cb_tmr1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cb_tmr2 {
            get {
                return ((int)(this["cb_tmr2"]));
            }
            set {
                this["cb_tmr2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cb_tmr3 {
            get {
                return ((int)(this["cb_tmr3"]));
            }
            set {
                this["cb_tmr3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cb_tmr4 {
            get {
                return ((int)(this["cb_tmr4"]));
            }
            set {
                this["cb_tmr4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cb_tmr5 {
            get {
                return ((int)(this["cb_tmr5"]));
            }
            set {
                this["cb_tmr5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cb_tmr6 {
            get {
                return ((int)(this["cb_tmr6"]));
            }
            set {
                this["cb_tmr6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Profile 4")]
        public string profile4 {
            get {
                return ((string)(this["profile4"]));
            }
            set {
                this["profile4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Profile 5")]
        public string profile5 {
            get {
                return ((string)(this["profile5"]));
            }
            set {
                this["profile5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Profile 6")]
        public string profile6 {
            get {
                return ((string)(this["profile6"]));
            }
            set {
                this["profile6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cb_trig_tmr1_desc {
            get {
                return ((string)(this["cb_trig_tmr1_desc"]));
            }
            set {
                this["cb_trig_tmr1_desc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cb_trig_tmr2_desc {
            get {
                return ((string)(this["cb_trig_tmr2_desc"]));
            }
            set {
                this["cb_trig_tmr2_desc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cb_trig_tmr3_desc {
            get {
                return ((string)(this["cb_trig_tmr3_desc"]));
            }
            set {
                this["cb_trig_tmr3_desc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cb_trig_tmr4_desc {
            get {
                return ((string)(this["cb_trig_tmr4_desc"]));
            }
            set {
                this["cb_trig_tmr4_desc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cb_trig_tmr5_desc {
            get {
                return ((string)(this["cb_trig_tmr5_desc"]));
            }
            set {
                this["cb_trig_tmr5_desc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cb_trig_tmr6_desc {
            get {
                return ((string)(this["cb_trig_tmr6_desc"]));
            }
            set {
                this["cb_trig_tmr6_desc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public decimal nud_coold {
            get {
                return ((decimal)(this["nud_coold"]));
            }
            set {
                this["nud_coold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Profile 7")]
        public string profile7 {
            get {
                return ((string)(this["profile7"]));
            }
            set {
                this["profile7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Profile 8")]
        public string profile8 {
            get {
                return ((string)(this["profile8"]));
            }
            set {
                this["profile8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Profile 9")]
        public string profile9 {
            get {
                return ((string)(this["profile9"]));
            }
            set {
                this["profile9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int chb_trig_once_0 {
            get {
                return ((int)(this["chb_trig_once_0"]));
            }
            set {
                this["chb_trig_once_0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int chb_trig_once_1 {
            get {
                return ((int)(this["chb_trig_once_1"]));
            }
            set {
                this["chb_trig_once_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int chb_trig_once_2 {
            get {
                return ((int)(this["chb_trig_once_2"]));
            }
            set {
                this["chb_trig_once_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int chb_trig_once_3 {
            get {
                return ((int)(this["chb_trig_once_3"]));
            }
            set {
                this["chb_trig_once_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int chb_trig_once_4 {
            get {
                return ((int)(this["chb_trig_once_4"]));
            }
            set {
                this["chb_trig_once_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int chb_trig_once_5 {
            get {
                return ((int)(this["chb_trig_once_5"]));
            }
            set {
                this["chb_trig_once_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_trig_time_0 {
            get {
                return ((decimal)(this["nud_trig_time_0"]));
            }
            set {
                this["nud_trig_time_0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_trig_time_1 {
            get {
                return ((decimal)(this["nud_trig_time_1"]));
            }
            set {
                this["nud_trig_time_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_trig_time_2 {
            get {
                return ((decimal)(this["nud_trig_time_2"]));
            }
            set {
                this["nud_trig_time_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_trig_time_3 {
            get {
                return ((decimal)(this["nud_trig_time_3"]));
            }
            set {
                this["nud_trig_time_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_trig_time_4 {
            get {
                return ((decimal)(this["nud_trig_time_4"]));
            }
            set {
                this["nud_trig_time_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_trig_time_5 {
            get {
                return ((decimal)(this["nud_trig_time_5"]));
            }
            set {
                this["nud_trig_time_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_trig_delay_0 {
            get {
                return ((decimal)(this["nud_trig_delay_0"]));
            }
            set {
                this["nud_trig_delay_0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_trig_delay_1 {
            get {
                return ((decimal)(this["nud_trig_delay_1"]));
            }
            set {
                this["nud_trig_delay_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_trig_delay_2 {
            get {
                return ((decimal)(this["nud_trig_delay_2"]));
            }
            set {
                this["nud_trig_delay_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_trig_delay_3 {
            get {
                return ((decimal)(this["nud_trig_delay_3"]));
            }
            set {
                this["nud_trig_delay_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_trig_delay_4 {
            get {
                return ((decimal)(this["nud_trig_delay_4"]));
            }
            set {
                this["nud_trig_delay_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_trig_delay_5 {
            get {
                return ((decimal)(this["nud_trig_delay_5"]));
            }
            set {
                this["nud_trig_delay_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int chb_log {
            get {
                return ((int)(this["chb_log"]));
            }
            set {
                this["chb_log"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cb_press_type {
            get {
                return ((int)(this["cb_press_type"]));
            }
            set {
                this["cb_press_type"] = value;
            }
        }
    }
}
